# Generated by Django 6.0.3 on 2026-03-06 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyurtma',
            name='tel_raqam',
            field=models.CharField(default='+998', max_length=20),
        ),
        migrations.AlterField(
            model_name='buyurtma',
            name='holati',
            field=models.CharField(default='Jarayonda', max_length=50),
        ),
        migrations.AlterField(
            model_name='buyurtma',
            name='manzil',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='BuyurtmaMahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soni', models.PositiveIntegerField()),
                ('narxi', models.PositiveIntegerField()),
                ('buyurtma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyurtma_dorilari', to='asosiy.buyurtma')),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.mahsulot')),
            ],
        ),
    ]
