# Generated by Django 6.0.3 on 2026-03-07 04:26

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0004_saralangan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyurtma',
            options={'ordering': ['-sana'], 'verbose_name': 'Buyurtma', 'verbose_name_plural': 'Buyurtmalar'},
        ),
        migrations.AlterModelOptions(
            name='buyurtmamahsulot',
            options={'verbose_name': 'Buyurtma mahsuloti', 'verbose_name_plural': 'Buyurtma mahsulotlari'},
        ),
        migrations.AlterModelOptions(
            name='izoh',
            options={'ordering': ['-sana'], 'verbose_name': 'Izoh', 'verbose_name_plural': 'Izohlar'},
        ),
        migrations.AlterModelOptions(
            name='kategoriya',
            options={'ordering': ['nomi'], 'verbose_name': 'Kategoriya', 'verbose_name_plural': 'Kategoriyalar'},
        ),
        migrations.AlterModelOptions(
            name='mahsulot',
            options={'ordering': ['-created_at'], 'verbose_name': 'Mahsulot', 'verbose_name_plural': 'Mahsulotlar'},
        ),
        migrations.AlterModelOptions(
            name='saralangan',
            options={'ordering': ['-qoshilgan_vaqt'], 'verbose_name': 'Saralangan', 'verbose_name_plural': 'Saralanganlar'},
        ),
        migrations.AlterModelOptions(
            name='savatcha',
            options={'ordering': ['-qoshilgan_vaqt'], 'verbose_name': 'Savatcha', 'verbose_name_plural': 'Savatcha'},
        ),
        migrations.AddField(
            model_name='kategoriya',
            name='slug',
            field=models.SlugField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='slug',
            field=models.SlugField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='saralangan',
            name='qoshilgan_vaqt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savatcha',
            name='qoshilgan_vaqt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buyurtma',
            name='foydalanuvchi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyurtmalar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='buyurtma',
            name='holati',
            field=models.CharField(choices=[('Jarayonda', 'Jarayonda'), ('Tasdiqlandi', 'Tasdiqlandi'), ('Yuborildi', 'Yuborildi'), ('Yetkazildi', 'Yetkazildi'), ('Bekor qilindi', 'Bekor qilindi')], default='Jarayonda', max_length=50),
        ),
        migrations.AlterField(
            model_name='buyurtma',
            name='jami_summa',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='buyurtmamahsulot',
            name='mahsulot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyurtma_mahsulotlari', to='asosiy.mahsulot'),
        ),
        migrations.AlterField(
            model_name='buyurtmamahsulot',
            name='soni',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='izoh',
            name='foydalanuvchi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='izohlar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kategoriya',
            name='nomi',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='mahsulot',
            name='kategoriya',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mahsulotlar', to='asosiy.kategoriya'),
        ),
        migrations.AlterField(
            model_name='mahsulot',
            name='narxi',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='saralangan',
            name='foydalanuvchi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saralanganlar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='saralangan',
            name='mahsulot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yoqtirilganlar', to='asosiy.mahsulot'),
        ),
        migrations.AlterField(
            model_name='savatcha',
            name='foydalanuvchi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savatcha_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='savatcha',
            name='mahsulot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savatchada', to='asosiy.mahsulot'),
        ),
        migrations.AlterField(
            model_name='savatcha',
            name='soni',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterUniqueTogether(
            name='saralangan',
            unique_together={('foydalanuvchi', 'mahsulot')},
        ),
        migrations.AlterUniqueTogether(
            name='savatcha',
            unique_together={('foydalanuvchi', 'mahsulot')},
        ),
    ]
